export const ADMIN_INIT_REQUEST = "admin/INIT_REQUEST";
export type ADMIN_INIT_REQUEST = typeof ADMIN_INIT_REQUEST;

export const ADMIN_SET_ACTIVE_TAB = "admin/SET_ACTIVE_TAB";
export type ADMIN_SET_ACTIVE_TAB = "admin/SET_ACTIVE_TAB";

export const ADMIN_SET_QUERY = "admin/SET_QUERY";
export type ADMIN_SET_QUERY = typeof ADMIN_SET_QUERY;

export const ADMIN_SET_ACTIVE_ITEM_ID = "admin/SET_ACTIVE_ID";
export type ADMIN_SET_ACTIVE_ITEM_ID = typeof ADMIN_SET_ACTIVE_ITEM_ID;

export const ADMIN_UPDATE_RESUME_ITEM_REQUEST = "admin/UPDATE_RESUME_ITEM";
export type ADMIN_UPDATE_RESUME_ITEM_REQUEST = typeof ADMIN_UPDATE_RESUME_ITEM_REQUEST;
export const ADMIN_CREATE_RESUME_ITEM_REQUEST = "admin/CREATE_RESUME_ITEM";
export type ADMIN_CREATE_RESUME_ITEM_REQUEST = typeof ADMIN_CREATE_RESUME_ITEM_REQUEST;
export const ADMIN_DELETE_RESUME_ITEM_REQUEST = "admin/DELETE_RESUME_ITEM";
export type ADMIN_DELETE_RESUME_ITEM_REQUEST = typeof ADMIN_DELETE_RESUME_ITEM_REQUEST;

export const ADMIN_UPDATE_WORK_ITEM_REQUEST = "admin/UPDATE_WORK_ITEM";
export type ADMIN_UPDATE_WORK_ITEM_REQUEST = typeof ADMIN_UPDATE_WORK_ITEM_REQUEST;
export const ADMIN_CREATE_WORK_ITEM_REQUEST = "admin/CREATE_WORK_ITEM";
export type ADMIN_CREATE_WORK_ITEM_REQUEST = typeof ADMIN_CREATE_WORK_ITEM_REQUEST;
export const ADMIN_DELETE_WORK_ITEM_REQUEST = "admin/DELETE_WORK_ITEM";
export type ADMIN_DELETE_WORK_ITEM_REQUEST = typeof ADMIN_DELETE_WORK_ITEM_REQUEST;
