export const ADMIN_LOGIN_REQUEST = "auth/ADMIN_LOGIN_REQUEST";
export type ADMIN_LOGIN_REQUEST = typeof ADMIN_LOGIN_REQUEST;

export const ADMIN_LOGIN_SUCCESS = "auth/ADMIN_LOGIN_SUCCESS";
export type ADMIN_LOGIN_SUCCESS = typeof ADMIN_LOGIN_SUCCESS;

export const ADMIN_LOGOUT_REQUEST = "auth/ADMIN_LOGOUT_REQUEST";
export type ADMIN_LOGOUT_REQUEST = "auth/ADMIN_LOGOUT_REQUEST";

export const DESTROY_ADMIN_SESSION = "auth/DESTROY_ADMIN_SESSION";
export type DESTROY_ADMIN_SESSION = typeof DESTROY_ADMIN_SESSION;
