export const ADMIN_LOGIN_REQUEST = "auth/ADMIN_LOGIN_REQUEST";
export type ADMIN_LOGIN_REQUEST = typeof ADMIN_LOGIN_REQUEST;

export const ADMIN_LOGIN_SUCCESS = "auth/ADMIN_LOGIN_SUCCESS";
export type ADMIN_LOGIN_SUCCESS = typeof ADMIN_LOGIN_SUCCESS;
